typography_spectrum: 0.4287095342297107
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.6830655732192099
  lightness: 0.6692902359645814
  saturation: 0.9622790503781289
  rhythmicContrast: 0.6552141190040857
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.45522165414877236
analytics:
  google: null
  facebook: null
  twitter: null
name: michaelnaegeli
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Michael E. Nägeli
description: Unternehmer
purpose: []
